### ISSUE TITLE
Module not found: Error: Can't resolve 'path' in 'node_modules\@nunomaduro\dd\dist'

### ISSUE THREAD

**Issue by nelson6e65** [nunomaduro/dd#12]
I'm trying to import in my TypeScript file but I get that error.

```ts
import dd from '@nunomaduro/dd';
```

Seems to be using `'path'` package, but is not listed in `dependencies` or `peerDependencies`

https://github.com/nunomaduro/dd/blob/3e45cd0cf62fb0343c5c86d3b2abe542677bcff6/src/concerns/findSourceCall.ts#L1

https://github.com/nunomaduro/dd/blob/3e45cd0cf62fb0343c5c86d3b2abe542677bcff6/package.json#L31-L33

**Comment by nelson6e65** [comment]
I installed 'path' (`npm i -D path`) but I get this warning from Angular:

```
node_modules\@nunomaduro\dd\dist\dd.esm.js depends on 'path'. 
CommonJS or AMD dependencies can cause optimization bailouts
```

Or this is not for client? 😅

**Comment by nunomaduro** [comment]
This is node only.

**Comment by nelson6e65** [comment]
I see. 

> **Off topic question:**
> It can be used in a TypeScript script, with `ts-node`?
> I tried to use in a direct script, but get some error too. (I'll check in a new issue when I get my PC,, but just asking).
