### ISSUE TITLE
Introducing Ship.js

### ISSUE THREAD

**Issue by eunjae-lee** [nunomaduro/dd#4]
As you may know, I'm maintaining [Ship.js](https://github.com/algolia/shipjs).
Now that I see you releasing js packages, I just wanted to give you a little demo about it.

I've forked your repo and ran the following command:

```bash
npx shipjs setup
```

![image](https://user-images.githubusercontent.com/499898/71799245-2b6dcd80-3098-11ea-8ab5-8697ebe88d52.png)

And I made a commit from the changes: https://github.com/eunjae-lee/dd/commit/c4779fd9c3234da2fc76c4355abcc15a0a6057a9

Except for the CircleCI config file, the change is little.
If you get more interested, let me know 🙂

**Comment by nunomaduro** [comment]
@eunjae-lee Thank you so much for this buddy! I am really sorry, but I am happy about the current release process: https://github.com/nunomaduro/dd/blob/master/scripts/release.sh.

Thanks for proposing this tho!

**Comment by nunomaduro** [comment]
@eunjae-lee Thank you so much for this buddy! I am really sorry, but I am happy about the current release process: https://github.com/nunomaduro/dd/blob/master/scripts/release.sh.

Thanks for proposing this tho!

**Comment by eunjae-lee** [comment]
No worries! Just wanted to show you how it's done 🙂
